### ISSUE TITLE
Change Goggles Lens keybind cannot be changed

### ISSUE THREAD

**Issue by xJon** [KELETU66666/Isorropia_kedition#1]
It is hardcoded to `V` over https://github.com/KELETU66666/Isorropia_kedition/blob/master/src/main/java/fr/wind_blade/isorropia/common/events/KeyHandler.java#L24, and cannot be effectively changed in-game.

**Comment by KELETU66666** [comment]
[IcarussOne](https://github.com/IcarussOne)
